export const OPEN_DIALOG_EVENT = 'OPEN_DIALOG_EVENT';

export const RECORD_EVENT_TITLE = 'RECORD_EVENT_TITLE';

export const RECORD_DATE = 'RECORD_DATE';
export const RECORD_HOUR = 'RECORD_HOUR';
export const RECORD_DURATION = 'RECORD_DURATION';

export const RECORD_FREQUENCY = 'RECORD_FREQUENCY';
// export const RECORD_MULTIPLES_DAYS = 'RECORD_MULTIPLES_DAYS';
