export const POST_EVENT = 'POST_EVENT';
export const POST_EVENT_SUCCES = 'POST_EVENT_SUCCES';
export const POST_EVENT_FAILED = 'POST_EVENT_FAILED';

export const GET_EVENT_LIST = 'GET_EVENT_LIST';
export const GET_EVENT_LIST_SUCCES = 'GET_EVENT_LIST_SUCCES';
export const GET_EVENT_LIST_FAILED = 'GET_EVENT_LIST_FAILED';
